try:
	print('Testing'.s)
except Exception as err:	
	print('Terjadi Kesalahan')
finally:
	print('finally')